# Generated by Django 4.1.3 on 2022-11-19 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_product_tag_delete_products_order_customer_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Products',
        ),
        migrations.RenameModel(
            old_name='Tag',
            new_name='Tags',
        ),
    ]
